const khodamNames = [
  "Macan Gobang",
  "Udin Petot",
  "Indomi Kecut",
  "Harimau Jawir",
  "Monyet Selangkangan",
  "Joko Cangkir",
  "Ronaldowati",
  "Raffi Rahmat",
  "Neymar Bogor",
  "Ikan Sepat",
  "Kera Sakit",
  "Monyet Liar",
  "Lintah Darat",
  "Ceker Bebek",
  "Budiono Siregar",
  "Asep Cepirit",
  "Ular Ceplok",
  "Kambing Gulai",
  "Siluman Joko",
  "Siluman Asep",
  "Terompet Sangkakala",
  "Burung Garuda",
  "Paul Nyeker",
  "Kobra Gurun",
  "Curut Kejepit",
  "Ceker Onta",
  "Kontolodon",
  "Basuri",
  "Gaada Khodam",
  "Aniez",
  "Abah",
  "Lele Cobek",
  "Genderuwo",
  "Naga Hitam",
  "Sound Sistem",
  "Samsung J2 Prime",
  "Ganjar 16%",
  "Ma'ruf amin",
  "Roger Sumatera",
  "Sapi Qurban",
  "Harimau Melompat",
  "Kucing Tidur",
  "Naga Terbang",
  "Burung Bernyanyi",
  "Ular Menggeliat",
  "Gajah Berjalan",
  "Singa Mengaum",
  "Kuda Berlari",
  "Khodam Pikachu Ngereog",
  "Khodam Sempak Bolong",
  "Hantu Galau",
  "Tuyul Tertawa",
  "Kuntilanak Narsis",
  "Genderuwo Pemalu",
  "Pocong Berlari",
  "Setan Gundul",
  "Jenglot Melambai",
  "Lele Menyanyi",
  "Bebek Joget",
  "Ayam Terbang",
  "Kelinci Keren",
  "Domba Santai",
  "Kambing Guling",
  "Sapi Terbang",
  "Buaya Ngamuk",
  "Harimau Bernyanyi",
  "Singa Menari",
  "Ikan Lompat",
  "Udang Nyengir",
  "Kepiting Joget",
  "Kerang Ngompol",
  "Babi Hutan Ngamuk",
  "Gajah Menari",
  "Monyet Terbang",
  "Burung Gagak",
  "Buaya Muara",
  "Macan Putih",
"Bebek Goreng",
"Ayam Geprek",
"Singa Putih",
"Buku Gambar",
"Buku Tulis",
"Penggaris",
"Papan Tulis",
"Gunting Kuku",
"Harimau",
"Macan Tutul",
"Anime",
"Macan Ompong",
"Es Teh",
"TEH JUS",
"Marimas Anggur",
"Teh Gelas",
"Jus Alpukat",
"Puntung Rokok",
"Ubur Ubur",
"Remote TV",
"Cacing Buncit",
"Monyet Mullet",
"Knalpot Mio",
"Mie Ayam",
"Bakso",
"Bakso Cuanki",
"Sumpit Gacoan",
"Standar Motor",
"Pala Mio",
"Beat Karbu",
"Jerapah",
"Badak Hitam",
"Lumba Lumba",
"Laba Laba Sunda",
"Ambatukam",
"Ambatron",
"Kelly FF",
"Kopi ABC",
"Kapal Lawut",
"Tunggu Kiris",
"Keris Tumpul",
"Kak Gem",
"Uni Bakwan",
"Sprei Gratis",
"Mejikom",
"Kuali Goreng",
"Kuah Soto",
"Cilok Idaman",
"Batagor",
"Siomay",
"Kue Pancong",
"Kipas Angin",
"Topi Upacara",
"Sepatu Adidas",
"RAJA IBLIS",
"Banaspati",
"Air Cucian Beras",
"Remote AC",
"Kosong",
"Sosok Hitam",
"Si Imut",
"Chargeran",
"Kabel Type C",
"Nenek Gayung",
"Vampire Ompong",
"Bajing Loncat",
"Ular Sawah",
"Ubi Cilembu",
"Pencil 2B",
"Korek Api",
"Ukelele",
"Pecel Lele",
"Ondel Ondel",
"Kuda Poni",
"Kuda Lumping",
"Sound System",
"Polisi Tidur",
"Ban Dalem",
"Sempak Bolong",
"Kue Pancong",
"Seblak",
"Seblak Ceker",
"Sarimi Ayam Bawang",
"Balmond",
"Mesin Bubut",
"Sate Biawak",
"Katak Bhizer",
"Kolor Ijo",
"Kucing",
"Kecebong",
"Ikan Mujaer",
"Ayam Bakar",
"Mie Gacoan",
"Kipas Angin",
"Panci Warteg",
"Jangrik Krispi",
"Sikat Gigi",
"Mesin Cuci",
"Vas Bunga",
"Kuntilanak Mewing",
"Pocong Ngesot",
"Sabun Colek",
"Pisau Dapur",
"Mio Mirza",
"Kaleng Sarden",
"Kursi Goyang",
"Masako Ayam",
"Tutup Botol",
"Undur Undur",
"Buaya Buntung",
"Celana Levis",
"Kuda Terbang",
"Cicak",
"Es Cendol",
"Ikan Hiu",
"Marimas Jeruk",
"Ikan Lohan",
"Pohon Kelapa",
"Sendal Swalow",
"Tikus Got",
"Singa Paddlepop",
"Ayam Warna Warni",
"Minyak Kayu Putih",
"Pulpen",
"Fresh Care",
"Martabak Manis",
"Martabak Asin",
"Casing HP",
"Mangkok Mie Ayam",
"Tahu Bulat",
"Garpu Siomay",
"Lontong Sayur",
"Es Kul Kul",
"Ayam Rechesee",
"Udang Saos Tiram",
"Bakso Beranak",
"Stang Motor",
"Belut Sawah",
"Ular Tangga",
"Gajah Duduk",
"Pisang Goreng",
"Spion Motor",
"Bubur Ayam",
"Tabung Gas",
"Bingkai Foto",
"Laler",
"Rengginang",
"Keset Selamat Datang",
"Kera Putih",
"Sempol Ayam",
"Bintang Laut",
"Sayur Asem",
"Tempe Bacem",
"Jepit Jemuran",
"Ikan Sapu Sapu",
"Royco Sapi",
"Tahu Gejrot",
"Masako Sapi",
"Royco Ayam",
"Sayur Lodeh",
"Jagung Bakar",
"Telur Dadar",
"Musang",
"Kanebo",
"Sabun Cuci Steam",
"Kadal Gurun",
"Domba Garut",
"Sapi Qurban",
"Barbie",
"Kelereng",
"Kuda Catur",
"Kue Putu",
"Ulat Bulu",
"Pangsit",
"Bakpau Isi Kacang",
"Kecoa Dubia",
"Naga Bearbrend",
"Pesulap Merah",
"Toji Kerupuk",
"Pohon Bijak",
"Tisu Toilet",
"Daun Pisang",
"Batu Bata",
"Cumi Cumi",
"Ale Ale",
"Telur Puyuh",
"Rujak Asem",
"Ceker Babat",
"Tuyul Wolfcut",
"Handuk Hotel",
"Sendal Jepit",
"Rokok Fajar",
"Ketupat",
"Nasi Kuning",
"Nasi Uduk",
"Kerak Telor",
"Nasi Liwet",
"Boboiboy Kuasa Sigma",
"Ember Bocor"
];
$("#namaInput").keypress(function(event) {
    if (event.keyCode === 13) {
        event.preventDefault(); 
        HandleClick();
    }
});
$("#cek").click(function () {
    HandleClick()
});
function HandleClick() {
  var inputNama = $("#namaInput").val().trim();

  if (inputNama !== "") {
    $("#nama").text(inputNama);

    var randomIndex = Math.floor(Math.random() * khodamNames.length);
    var hasilKhodam = khodamNames[randomIndex];
    var teksToSpeak = inputNama + ". Khodamnya adalah " + hasilKhodam;

    $("#hasilkhodam").text(hasilKhodam);

    var msg = new SpeechSynthesisUtterance(teksToSpeak);
    msg.rate = 1.2;
    msg.pitch = 1.2;
    msg.lang = "id-ID";
    window.speechSynthesis.speak(msg);
  } else {
    alert("Silakan masukkan nama untuk dicek.");
  }
};

$("#reset").click(function () {
  $("#namaInput").val("");
  $("#nama").text("");
  $("#hasilkhodam").text("");
});
